FROM oven/bun:1

WORKDIR /app

# COPY  ../apps/http-server/package.* .
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json 
COPY ./package.json  ./package.json

COPY ./apps/http-server ./apps/http-server
RUN bun install 
RUN bun run db:generate

EXPOSE 8080

CMD ["bun","run","start:http"]