name: http backand deploying
on: 
   push:
     branches:
      - main
jobs: 

   buildImage: 
        name: building docker image 
        runs-on: ubuntu-latest
        steps:
         - name: checkout the repo
           uses: actions/checkout@v4

         - name: login to docker hub
           uses: docker/login-action@v3
           with: 
             username: ${{secrets.DOCKERHUB_USERNAME}}
             password: ${{secrets.DOCKERHUB_PASSWORD}}

         - name: build and push to docker hub
           uses: docker/build-push-action@v6
           with: 
             context: .
             file: ./docker/Dockerfile.backend
             push: true
             tags: itzlg/monorepo-ci-cd-backend:${{github.sha}}
          
             
           
