name: http backand deploying
on: 
   push:
     branches:
      - main
jobs: 

   buildImage: 
        name: building docker image 
        runs-on: ubuntu-latest
        steps:
         - name: checkout the repo
           uses: actions/checkout@v4

         - name: login to docker hub
           uses: docker/login-action@v3
           with: 
             username: ${{secrets.DOCKERHUB_USERNAME}}
             password: ${{secrets.DOCKERHUB_PASSWORD}}

         - name: build and push to docker hub
           uses: docker/build-push-action@v6
           with: 
             context: .
             file: ./docker/Dockerfile.backend
             push: true
             tags: itzlg/monorepo-ci-cd-backend:${{github.sha}}
          
         - name: deploy to vm
           run: |
             echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
             ls ~/ssh_key
             chmod 700 ~/ssh_key
             ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{secrets.HOST_IP}} -t << 'EOF'
              docker stop user_backend
              docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} --name user_backend itzlg/monorepo-ci-cd-backend:${{secrets.github_sha}}
             EOF
             
           
