name: websocket deploying
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout the repo
        uses: actions/checkout@v4

      - name: login to docker-hub
        uses: docker/login-action@v3
        with: 
           username: ${{secrets.DOCKERHUB_USERNAME}}
           password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: itzlg/monorepo-ci-cd-ws:${{github.sha}}
    
      - name: removing existing container and image
        uses: Lovegupta112/cleanup-docker-container-img@v1.0.1
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          HOST_IP: ${{secrets.HOST_IP}}
          CONTAINER_NAME: ${{secrets.WS_CONTAINER_NAME}}
        

      - name: start the container
        run: | 
              echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key 
              chmod 700 ~/ssh_key 
              ssh -o StrictHostKeyChecking=no -i ~/ssh_key ${{secrets.HOST_IP}} -t << 'EOF'
              docker run -d -p 8081:8081 \
              -e DATABASE_URL=${{secrets.DATABASE_URL}} \
              --name ${{secrets.WS_CONTAINER_NAME}} itzlg/monorepo-ci-cd-ws:${{github.sha}} 
              EOF
             
         